---
- name: Backup Cisco Switches or Router
  hosts: all
  gather_facts: false
  
  tasks:
  - name: Collect all facts from the device
    ios_facts:
      gather_subset: all

  #Finale task save running-config
  - name: Save backup running-config
    ios_config:
      backup: yes
      backup_options:
         filename: "{{ ansible_net_hostname }}_{{ inventory_hostname }}.cfg"
         dir_path: ./backups/
