---
- name: Add new users and privilege level
  cisco.ios.ios_user:
    aggregate:
      - name: "{{ user_new }}"
        configured_password: "{{ password_new }}"
        password_type: password
    privilege: "{{ privilege_new }}"
    state: present
  when: password_new is defined
