---
- name: Add new users and privilege level
  cisco.ios.ios_user:
    aggregate:
      - name: "{{ user_new }}"
        configured_password: "{{ password_new }}"
        password_type: password
    privilege: "{{ privilege_new }}"
    state: present
  when: user_new is defined

- name: Update Password
  cisco.ios.ios_user:
    name: "{{ user_update }}"
    configured_password: '{{ update_password }}'
    update_password: always
    state: present
  when: user_update is defined

- name: Delete users
  cisco.ios.ios_user:
    aggregate:
    - name:  "{{ user_delete }}"
    state: absent
  when: user_delete is defined
