---
- name: Create root directory if don't exist
  file:
    path: "{{ backup_folder }}"
    state: directory
    mode: 0755

- name: Create individual device folder if don't exist
  file:
    path: "{{ backup_folder }}{{ inventory_hostname }}"
    state: directory
    mode: 0755 

- name: Register timestamp variable
  local_action: command date +%Y%m%d-%H:%M
  register: timestamp

- name: BACKUP THE CONFIG
  cisco.ios.ios_config:
    provider: "{{ cli }}"      
    backup: yes
    backup_options:
      dir_path: ./backup
  register: config_output

- name: Execute IOS commands
  ios_command:
    provider: "{{ cli }}"
    commands: "{{ item  }}"
  register: commands_output
  with_items:
   - show run
   - write
   - show ip interface brief 
   - show interfaces summary
   - show etherchannel summary
   - show logging
   - show version
   - show spanning-tree
   - show spanning-tree blockedports
  when: 
   - cisco_os == 'ios'

- name: Create IOS command folder if don't exist
  file:
    path: "{{ backup_folder }}{{ inventory_hostname }}/{{ commands_output.results[item].item }}"
    state: directory
    mode: 0755
  with_items:
   - 0
   - 1
   - 2 
   - 3
   - 4
   - 5
   - 6
   - 7
   - 8
  when:
    - cisco_os == 'ios'

- name: Save IOS command output on destination file
  copy:
    content: "{{ commands_output.results[item].stdout[0] }}"
    dest:  "{{ backup_folder }}{{ inventory_hostname }}/{{ commands_output.results[item].item }}/{{ inventory_hostname }}_{{ commands_output.results[item].item }}_{{ timestamp.stdout }}.txt"
  with_items:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8 
  when:
    - cisco_os == 'ios'
